[phases.setup]
nixPkgs = [
    "php84",
    "php84Packages.composer",
    "nodejs_20",
    "php84Extensions.pdo_mysql",
    "php84Extensions.gd",
    "php84Extensions.zip",
    "php84Extensions.mbstring",
    "php84Extensions.xml",
    "php84Extensions.curl",
    "php84Extensions.mysqlnd"
]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "php artisan winter:mirror public",
]

[start]
cmd = "php artisan winter:up && php artisan serve --host=0.0.0.0 --port=80"
